services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - ./frontend/.env
    networks:
      - fullstack_dictionary_net
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3030:3030"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./api/.env
    networks:
      - fullstack_dictionary_net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack_dictionary_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  fullstack_dictionary_net:
    name: fullstack_dictionary_net

