services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - ./frontend/.env
    networks:
      - fullstack_dictionary_net
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3030:3033"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./api/.env
    networks:
      - fullstack_dictionary_net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fullstack_dictionary_net
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack_dictionary_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  fullstack_dictionary_net:
    name: fullstack_dictionary_net

